export {
  // Constants
  BRAND_NAME,
  BRAND_NAME_FULL,
  BRAND_DOMAIN,
  API_VERSION,
  API_PREFIX,
  JWT_EXPIRY_SECONDS,
  REFRESH_TOKEN_EXPIRY_SECONDS,
  BCRYPT_ROUNDS,
  MAX_LOGIN_ATTEMPTS,
  LOGIN_LOCKOUT_MINUTES,
  DEFAULT_PAGE,
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  WS_RECONNECT_DELAYS_MS,
  WS_HEARTBEAT_INTERVAL_MS,
  WS_PAYLOAD_VERSION,
  PLACEHOLDER_ROUND_DURATION_SECONDS,
  PLACEHOLDER_LOCK_PERIOD_SECONDS,
  PLACEHOLDER_ROUND_GAP_SECONDS,
  TARGET_FPS,
  TARGET_API_LATENCY_MS,
  TARGET_WS_LATENCY_MS,
  TARGET_TTI_SECONDS,
  TARGET_RECONNECT_SECONDS,
} from './constants';

export type { EnvironmentConfig } from './environment';
export {
  getEnvOrThrow,
  getEnvOrDefault,
  getEnvIntOrDefault,
  isProduction,
  isDevelopment,
  isTest,
} from './environment';
